---
title: "Win-Loss"
author: "Jack Schroeder"
date: "9/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

mlb <- read_csv("mlb_elo.csv")

```

```{r}
mlb%>%
  filter(season >1995,game_number <= 162)%>%
  mutate(home_score = score1,
         away_score = score2)%>%
  select(-score1, -score2)%>%
  mutate(win = case_when(home_score > away_score & home == "team1"  ~ 1,
                         home_score < away_score & home == "team1"  ~ 0,
                         home_score < away_score & home == "team2"  ~ 1,
                         home_score > away_score & home == "team2"  ~ 0))%>%
  group_by(season, team)%>%
  mutate(games=n(), win_percentage = (sum(win, na.rm = TRUE)/games))
  

  
  


```


```{r}
<<<<<<< HEAD
playoffs<-mlb%>%filter(game_number > 162)
=======
for(i in 1:length(mlb$game_number)){
  if(mlb$game_number[i] > 162){
    mlb$playoff[i] <- 1
  }
  else{mlb$playoff[i] <- 0}
}


```


```{r}
>>>>>>> 7f376e15e5b23aa3af7de5817eb490950798217c

  score1<score2 ~ "team2"))%>%
  mutate(win = case_when(home == winner ~ 1,
                         home != winner ~ 0))
```

```{r}
mlb%>%
  filter(season == 1996,game_number <= 162, team == "TEX")%>%
  mutate(home_score = score1,
         away_score = score2)%>%
  select(-score1, -score2)%>%
  mutate(win = case_when(home_score > away_score & home == "team1"  ~ 1,
                         home_score < away_score & home == "team1"  ~ 0,
                         home_score < away_score & home == "team2"  ~ 1,
                         home_score > away_score & home == "team2"  ~ 0))%>%
  group_by(season, team)%>%
  mutate(wins = sum(win, na.rm = TRUE))
```


